feat:Se añadio el método GetGroupByName sin %LIKE%
GaelRS/Docker_SD pull request #13
Opened 2024-09-25 23:35 UTC by GaelRS

2024-09-26 02:54 UTC, Jessfer68 requested changes

2024-09-26 02:54 UTC, Jessfer68 commented on RestApi/Controllers/GroupsController.cs
> +    [HttpGet]
Este quitalo, y deja el metodo del controller. Solo les pedi que agregaran el metodo en el repositorio, no que crearan un controller nuevo

2024-09-26 03:51 UTC, GaelRS commented on RestApi/Controllers/GroupsController.cs
> +    [HttpGet]
Listo profe, ya lo elimine del controller.

2024-10-25 21:28 UTC, Jessfer68 approved these changes
Procura no dejar codigo comentado, es mala practica

2024-10-28 17:55 UTC, merged